### ISSUE TITLE
Voice Biometrics

### ISSUE THREAD

**Issue by GeetaKrishna** [rfrobisher/node-voicegateway-soe#1]
This is not an issue. A small Doubt. How do we add the Voice Biometrics feature to the SOE?

**Comment by xurzua** [comment]
Hi @GeetaKrishna, 

What you mean by "Voice Biometrics Feature" ? Can you elaborate a little more ? (examples, docs, links).

Regards.

X.

**Comment by GeetaKrishna** [comment]
Anything that mostly sheds light on how to add those features to my SOE. Examples, docs these two can help me. I'll try to figure it out.

**Comment by sumitbhavra** [comment]
Hi Geeta,

According to my knowledge you can't integrate voice gateway with Voice biometrics. Voice gateway only supports IBM text to speech / speech to text and google voice. Voice biometrics is nuance proprietary. May be IBM will allow it in future. Will let you know if I come across its integration with voice gateway.

Regards
Sumit

**Comment by GeetaKrishna** [comment]
Ok Sumit. Thank you for the Information.
